jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies for SFML
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgl1-mesa-dev \
          libxrandr-dev \
          libxi-dev \
          libudev-dev \
          libopenal-dev \
          libvorbis-dev \
          libogg-dev \
          libflac-dev \
          libsfml-dev \
          libx11-dev \
          libxext-dev \
          libxtst-dev \
          libasound2-dev \
          libxcursor-dev  # Ensures the header files for Xcursor are available
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake ..
        make
